### ISSUE TITLE
Create initial UI sketches

### ISSUE THREAD

**Issue by fabianmuehlboeck** [Tateology/kaeru#6]
@Hapa29 

(of important parts of the web page). Refer to the [Requirements on the Wiki](https://github.com/Tateology/kaeru/wiki/Requirements).

**Comment by Hapa29** [comment]
First draft sketch of the landing page
![landingpage_firstdraft](https://cloud.githubusercontent.com/assets/3515686/6613865/10485602-c869-11e4-8018-ba244e3b496f.png)

**Comment by Hapa29** [comment]
First draft sketches of the IDE. There are three basic types I've skteched out:

1. Tabs in a Tab
2. Separate Tabs
These have been drawn in the same tab because the design I was thinking of is almost the exact same for both, just one has tabs within the same tab in the browser, and the other would actually open another tab in the browser.
![idetabs_firstdraft](https://cloud.githubusercontent.com/assets/3515686/6613885/55a5d832-c869-11e4-9c20-94bd5e6be286.png)

3. Side-by-Side Windows
![idewindows_firstdraft](https://cloud.githubusercontent.com/assets/3515686/6613899/6b04f578-c869-11e4-9894-0b1cfc4a4b6e.png)

I'll bring hard copies of the sketches to the meeting Friday so I can explain them better if they are unclear

**Comment by RossTate** [comment]
I like option 3. As for the splash page, it'd be cool if there's a mini-interactive thing right there, though maybe the video serves that purpose. It's worth considering.

**Comment by Hapa29** [comment]
![landingpagedraft2](https://cloud.githubusercontent.com/assets/3515686/6734449/91a4470e-ce2e-11e4-9a73-b92fa36701de.png)

**Comment by Hapa29** [comment]
![ide_draft2](https://cloud.githubusercontent.com/assets/3515686/6734452/98432602-ce2e-11e4-83f0-644b421a7368.png)

**Comment by Hapa29** [comment]
![documentation_draft1](https://cloud.githubusercontent.com/assets/3515686/6734462/a8848f38-ce2e-11e4-8438-0a3ae11f1e82.png)

**Comment by Hapa29** [comment]
![contact people_draft1](https://cloud.githubusercontent.com/assets/3515686/6734477/b55dea92-ce2e-11e4-9200-c7f914c303a2.png)

**Comment by Hapa29** [comment]
Just posted drafts of all the pages I see us having for the site at the moment. I'm sure there will be more or we'll scrap some (do we want to people/conact page? make it part of the landing page?)

Please leave feedback or ask questions if anything is unclear

**Comment by fabianmuehlboeck** [comment]
I agree that the link to the documentation should be more visible, both on the landing page and in the IDE. Personally, I would flip the parts of the landing page as suggested on the side and have the link to the documentation right next to the "Try it!" link.

The IDE seems to still be missing some kind of project management window (i.e. supporting code files).

Typical documentation sides have a side-bar listing other classes that one can go to directly (not only the parent/children). Is there a special reason for omitting that? In any case, there should be a search-bar somewhere.

**Comment by Hapa29** [comment]
![landingpage_draft3](https://cloud.githubusercontent.com/assets/3515686/6837224/73e60c24-d320-11e4-8208-47ffafe13ffe.png)

![ide_fullmode_draft1](https://cloud.githubusercontent.com/assets/3515686/6837225/7856a43a-d320-11e4-82b2-d88ebe499e96.png)

**Comment by fabianmuehlboeck** [comment]
Looks good!

**Comment by RossTate** [comment]
Agreed.
